rules:
  - frontend:
      url: "proto.v1.RuntimeService/"
      methods: ["POST"]
    backend:
      url: "http://localhost:8080/"
    middlewares:
      - name: basic_auth
        config:
          users:
            - user: example
              # password must be hashed using MD5, SHA1, or BCrypt(recommended) using htpasswd
              password: $2y$10$F814ZwQPt8VHYIayIqeEReSeZz8dDCNX93/rKI82SqJu9I2Bn6Hau # password
              capabilities: [ "*" ]
          scope:
            action: "ping"
            attributes:
              client:
                type: grpc_payload
                index: 1
    hooks:
      - name: authz
        config:
          action: some_action
          attributes:
            project_resp:
              index: 1
              type: grpc_payload
              source: request
            group:
              index: 1
              type: grpc_payload
