run:
  timeout: 5m
  skip-dirs:
    - ui
output:
  format: colored-line-number
linters:
  enable-all: false
  disable-all: true
  enable:
    - vet
    - goimports
    - thelper
    - unconvert
    - revive
    - unused
    - gofmt
    - whitespace
    - misspell
    - govet
    - importas
    - protogetter
    - ineffassign
    - wastedassign
#    - gosec
#    - prealloc
#    - errcheck
#    - errorlint
#    - staticcheck
#    - gosimple
#    - gocritic
#    - goconst
#    - perfsprint
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
severity:
  default-severity: error