project_name: frontier

release:
  prerelease: auto

before:
  hooks:
    - make test
    - make ui

builds:
  - id: "frontier"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: frontier
    main: ./main.go
    ldflags:
      - -s -w -X github.com/raystack/frontier/config.Version={{.Tag}}
      - -X github.com/raystack/frontier/config.BuildCommit={{.FullCommit}}
      - -X github.com/raystack/frontier/config.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: "frontier-archive"
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - frontier
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:latest"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Tag }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Tag }}-amd64"
  - goos: linux
    goarch: arm64
    ids:
      - frontier
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:{{ .Tag }}-arm64"

nfpms:
  - maintainer: Raystack
    description: Identity and authorization system
    homepage: https://github.com/raystack/frontier
    license: Apache 2.0
    formats:
      - deb
      - rpm

scoops:
  - homepage: "https://github.com/raystack/frontier"
    description: "Identity and authorization system"
    license: Apache 2.0
    repository:
      owner: raystack
      name: scoop-bucket

brews:
  - name: frontier
    homepage: "https://github.com/raystack/frontier"
    description: "Identity and authorization system"
    repository:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "frontier"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com