with-expecter: true
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{ .InterfaceName | snakecase }}.go"
packages:
  github.com/raystack/frontier/internal/api/v1beta1:
    config:
      dir: "internal/api/v1beta1/mocks"
      all: true
  github.com/raystack/frontier/pkg/mailer:
    config:
      dir: "pkg/mailer/mocks"
      all: true
  github.com/raystack/frontier/billing/entitlement:
    config:
      dir: "billing/entitlement/mocks"
      all: true
  github.com/raystack/frontier/billing/credit:
    config:
      dir: "billing/credit/mocks"
      all: true
  github.com/raystack/frontier/billing/product:
    config:
      dir: "billing/product/mocks"
      all: true
  github.com/raystack/frontier/billing/stripetest:
    config:
      dir: "billing/stripetest/mocks"
      all: true