version: 1

# logging configuration
log:
  # debug, info, warning, error, fatal - default 'info'
  level: debug

# proxy configuration
proxy:
  services:
    - name: test
      host: 0.0.0.0
      # port where the proxy will be listening on for requests
      port: 5556

      # full path prefixed with scheme where ruleset yaml files are kept
      # e.g.:
      # local storage file "file:///tmp/rules"
      # GCS Bucket "gs://shield-bucket-example"
      ruleset: file://absolute_path_to_rules_directory

      # secret required to access ruleset
      # e.g.:
      # system environment variable "env://TEST_RULESET_SECRET"
      # local file "file:///opt/auth.json"
      # secret string "val://user:password"
      #
      # +optional
      # ruleset_secret: env://TEST_RULESET_SECRET