version: 1
log:
  level: debug

app:
  port: 8089
  ruleset: file:///Users/kartikverma/work/data-engineering/shield/ignore/rules
  resources_config_path: file:///Users/kartikverma/work/data-engineering/shield/ignore/resource
  identity_proxy_header: "X-Auth-Email"

proxy:
  services:
    - host: 0.0.0.0
      port: 5556
      ruleset: file:///Users/kartikverma/work/data-engineering/shield/ignore/rules
      resources_config_path: file:///Users/kartikverma/work/data-engineering/shield/ignore/resource
      identity_proxy_header: "X-Auth-Email"

db:
  driver: postgres
  url: postgres://shield:@localhost:5432/shield?sslmode=disable
  max_query_timeout: 1000ms

spicedb:
  host: 0.0.0.0
  port: 50052
  pre_shared_key: shield

newrelic:
  app_name: local-shield-v2
  license: e308f819064ac3e96012420aeca0d48d780cNRAL
  enabled: false
