version: "3.7"

services:
  pg:
    image: postgres:12
    environment:
      - POSTGRES_DB=shield
      - POSTGRES_USER=shield
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
