version: '3.7'

networks:
  backend:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './src:/app/src'
      - ./node_modules:/app/node_modules
    ports:
      - 5000:5000
    environment:
      DB_URI: postgresql://shield_dev@postgres:5432/shield_dev
      REDIS_URL: redis://redis:6379
    env_file:
      - ./.env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ['CMD', 'sh', '-c', 'curl -f http://localhost:5000/ping']
      interval: 20s
      timeout: 5s
      retries: 12
  postgres:
    image: 'postgres:11.10'
    environment:
      POSTGRES_USER: 'shield_dev'
      POSTGRES_DB: 'shield_dev'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./.temp/pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 4321:5432
  postgres-test:
    image: 'postgres:11.10'
    environment:
      POSTGRES_USER: 'shield_test'
      POSTGRES_DB: 'shield_test'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./.temp/postgres-test:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 4322:5432
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - backend
