name: End-to-end Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: install dependencies
        run: go mod tidy
      - name: test binaries
        run: make e2e-test