name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: install dependencies
        run: make install
      - name: test binaries
        run: make test