name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: install dependencies
        run: go mod tidy
      - name: run unit tests
        run: make test
      - name: Send coverage to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out