name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: install dependencies
        run: go mod tidy
      - name: test binaries
        env:
          POSTGRES_PASSWORD: postgres
        run: make test
      - name: Send coverage to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
  e2e-smoke-test:
    runs-on: ubuntu-latest
    services:
      pg1:
        image: postgres:12
        env:
          POSTGRES_DB: "shield"
          POSTGRES_USER: "shield"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 30s
          --health-timeout 30s
          --health-retries 3
      pg2:
        image: "postgres:12"
        env:
          POSTGRES_USER: "spicedb"
          POSTGRES_DB: "spicedb"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - "5431:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 30s
          --health-timeout 30s
          --health-retries 3
      spicedb:
        image: quay.io/authzed/spicedb:v1.0.0
        ports:
          - "8080:8080"
          - "50051:50051"
          - "50053:50053"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: install dependencies
        run: go mod tidy
      - name: install spicedb binary
        uses: https://hub.docker.com/r/authzed/spicedb
      - name: migrate spicedb
        run: spicedb migrate head --datastore-engine postgres --datastore-conn-uri postgres://spicedb:@pg2:5432/spicedb-one?sslmode=disable
      - name: start spicedb
        run: spicedb serve --grpc-preshared-key "shield" --grpc-no-tls --datastore-engine postgres --datastore-conn-uri postgres://spicedb:@pg2:5432/spicedb-one?sslmode=disable
      - name: run proxy tests
        env:
          POSTGRES_PASSWORD: postgres
        run: make e2e-smoke-test